# https://circleci.com/docs/2.0/language-java/ for more details
# Note: The parameters declaration is available in configuration version 2.1 and later.
# https://circleci.com/docs/2.0/reusing-config/#using-the-parameters-declaration
version: 2.1

executors:
  openjdk:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

commands:
  eval-echo-env:
    #environment:
    #  GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_key.json
    parameters:
      environment:
        type: enum
        enum: ["dev", "staging", "prod"]
    steps:
      - run:
          name: Eval, echo & concat params to a string
          command: |
            #eval echo \$`echo << parameters.environment >> | tr 'a-z' 'A-Z'`_GCP_KEY >> $BASH_ENV
            eval echo \$`echo << parameters.environment >> | tr 'a-z' 'A-Z'_GCP_KEY > /tmp/gcp-key.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-key.json' >> $BASH_ENV
            source $BASH_ENV 
            set | grep -i "gcp_key"
            set | grep -i "google"
            cat $GOOGLE_APPLICATION_CREDENTIALS

jobs:
  build:
    executor: openjdk
    #docker:
    #  # specify the version you desire here
    #  - image: circleci/openjdk:8-jdk

    #  # Specify service dependencies here if necessary
    #  # CircleCI maintains a library of pre-built images
    #  # documented at https://circleci.com/docs/2.0/circleci-images/
    #  # - image: circleci/postgres:9.4

    #working_directory: ~/repo

    #environment:
    #  # Customize the JVM maximum heap limit
    #  JVM_OPTS: -Xmx3200m
    #  TERM: dumb

    parameters:
     environment:
       type: enum
       enum: ["dev", "staging", "prod"]
   
    steps:
      - checkout
      - eval-echo-env:
          environment: << parameters.environment >>

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Set up shell variable
          command: |
            eval TEMP_KEY=`which javac`
            echo "JAVAC ENV from eval: $TEMP_KEY"
            echo "export JAV_PATH=$(which javac | tr 'a-z' 'A-Z')_AND_STUFF" >> $BASH_ENV
            source $BASH_ENV
            echo "JAV_PATH ENV from export: $JAV_PATH"
      - run:
          name: Read shell variable
          command: |
            echo "JAVAC ENV from variable $TEMP_KEY"
            echo "JAV_PATH ENV from variable $JAV_PATH"
      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradlew
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: ./gradlew cleanTest test
workflows:
  build-test:
    jobs:
      - build:
          environment: dev
